// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Admin: typeof import('./src/views/admin/admin.vue')['default']
    AdminHome: typeof import('./src/views/admin/admin-home.vue')['default']
    BasicFooter: typeof import('./src/components/layout/basic-footer.vue')['default']
    BasicHeader: typeof import('./src/components/layout/basic-header.vue')['default']
    BasicLayout: typeof import('./src/components/layout/basic-layout.vue')['default']
    Dashboard: typeof import('./src/components/admin/dashboard.vue')['default']
    Home: typeof import('./src/views/home/home.vue')['default']
    Img: typeof import('./src/components/common/img.vue')['default']
    Login: typeof import('./src/views/login.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NGrid: typeof import('naive-ui')['NGrid']
    NGridItem: typeof import('naive-ui')['NGridItem']
    NIcon: typeof import('naive-ui')['NIcon']
    NImage: typeof import('naive-ui')['NImage']
    NImageGroup: typeof import('naive-ui')['NImageGroup']
    NInput: typeof import('naive-ui')['NInput']
    NInputGroup: typeof import('naive-ui')['NInputGroup']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NMenu: typeof import('naive-ui')['NMenu']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NP: typeof import('naive-ui')['NP']
    NPopconfirm: typeof import('naive-ui')['NPopconfirm']
    NPopover: typeof import('naive-ui')['NPopover']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpace: typeof import('naive-ui')['NSpace']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    NTag: typeof import('naive-ui')['NTag']
    NText: typeof import('naive-ui')['NText']
    NUpload: typeof import('naive-ui')['NUpload']
    NUploadDragger: typeof import('naive-ui')['NUploadDragger']
    PictureList: typeof import('./src/components/admin/picture/picture-list.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Upload: typeof import('./src/views/upload/upload.vue')['default']
    UploadInfo: typeof import('./src/components/upload/upload-info.vue')['default']
    UploadList: typeof import('./src/components/upload/upload-list.vue')['default']
    UploadListItem: typeof import('./src/components/upload/upload-list-item.vue')['default']
    UserList: typeof import('./src/components/admin/user/user-list.vue')['default']
  }
}

export {}
