// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BasicFooter: typeof import('./src/components/layout/basic-footer.vue')['default']
    BasicHeader: typeof import('./src/components/layout/basic-header.vue')['default']
    BasicLayout: typeof import('./src/components/layout/basic-layout.vue')['default']
    Home: typeof import('./src/views/home/home.vue')['default']
    Img: typeof import('./src/components/common/img.vue')['default']
    Login: typeof import('./src/views/login.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NIcon: typeof import('naive-ui')['NIcon']
    NImage: typeof import('naive-ui')['NImage']
    NImageGroup: typeof import('naive-ui')['NImageGroup']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NP: typeof import('naive-ui')['NP']
    NPopconfirm: typeof import('naive-ui')['NPopconfirm']
    NPopover: typeof import('naive-ui')['NPopover']
    NSpace: typeof import('naive-ui')['NSpace']
    NText: typeof import('naive-ui')['NText']
    NUpload: typeof import('naive-ui')['NUpload']
    NUploadDragger: typeof import('naive-ui')['NUploadDragger']
    PreviewList: typeof import('./src/components/upload/preview-list.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Upload: typeof import('./src/views/upload/upload.vue')['default']
    UploadInfo: typeof import('./src/components/upload/upload-info.vue')['default']
  }
}

export {}
